src/Entity/Salary.php
<?php

namespace App\Entity;

use App\Repository\SalaryRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SalaryRepository::class)]
#[ORM\Table('salaries')]
class Salary
{
    #[ORM\Id]
    #[ORM\ManyToOne(targetEntity:Employee::class, inversedBy: 'salaries')]
    #[ORM\JoinColumn(name:'emp_no', referencedColumnName:'emp_no', nullable: false)]
    private ?Employee $emp_no = null;

    #[ORM\Column]
    private ?int $salary = null;

    #[ORM\Id]
    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $from_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $to_date = null;

    public function getEmpNo(): ?Employee
    {
        return $this->emp_no;
    }

    public function setEmpNo(?Employee $emp_no): static
    {
        $this->emp_no = $emp_no;

        return $this;
    }

    public function getSalary(): ?int
    {
        return $this->salary;
    }

    public function setSalary(int $salary): static
    {
        $this->salary = $salary;

        return $this;
    }

    public function getFromDate(): ?\DateTimeInterface
    {
        return $this->from_date;
    }

    public function setFromDate(\DateTimeInterface $from_date): static
    {
        $this->from_date = $from_date;

        return $this;
    }

    public function getToDate(): ?\DateTimeInterface
    {
        return $this->to_date;
    }

    public function setToDate(\DateTimeInterface $to_date): static
    {
        $this->to_date = $to_date;

        return $this;
    }
}

src/Form/SalaryType.php
<?php

namespace App\Form;

use App\Entity\Employee;
use App\Entity\Salary;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SalaryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('salary')
            ->add('from_date', null, [
                'widget' => 'single_text',
            ])
            ->add('to_date', null, [
                'widget' => 'single_text',
            ])
            ->add('emp_no', EntityType::class, [
                'class' => Employee::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Salary::class,
        ]);
    }
}

src/Controller/SalaryController.php
<?php

namespace App\Controller;

use App\Entity\Salary;
use App\Form\SalaryType;
use App\Repository\SalaryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/salary')]
final class SalaryController extends AbstractController
{
    #[Route(name: 'app_salary_index', methods: ['GET'])]
    public function index(SalaryRepository $salaryRepository): Response
    {
        return $this->render('salary/index.html.twig', [
            'salaries' => $salaryRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_salary_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $salary = new Salary();
        $form = $this->createForm(SalaryType::class, $salary);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($salary);
            $entityManager->flush();

            return $this->redirectToRoute('app_salary_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('salary/new.html.twig', [
            'salary' => $salary,
            'form' => $form,
        ]);
    }

    #[Route('/{emp_no}', name: 'app_salary_show', methods: ['GET'])]
    public function show(Salary $salary): Response
    {
        return $this->render('salary/show.html.twig', [
            'salary' => $salary,
        ]);
    }

    #[Route('/{emp_no}/edit', name: 'app_salary_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Salary $salary, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(SalaryType::class, $salary);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_salary_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('salary/edit.html.twig', [
            'salary' => $salary,
            'form' => $form,
        ]);
    }

    #[Route('/{emp_no}', name: 'app_salary_delete', methods: ['POST'])]
    public function delete(Request $request, Salary $salary, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$salary->getEmp_no(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($salary);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_salary_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/salary/_delete_form.html.twig
<form method="post" action="{{ path('app_salary_delete', {'emp_no': salary.emp_no}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ salary.emp_no) }}">
    <button class="btn">Delete</button>
</form>

templates/salary/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/salary/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Salary{% endblock %}

{% block body %}
    <h1>Edit Salary</h1>

    {{ include('salary/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_salary_index') }}">back to list</a>

    {{ include('salary/_delete_form.html.twig') }}
{% endblock %}

templates/salary/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Salary index{% endblock %}

{% block body %}
    <h1>Salary index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Salary</th>
                <th>From_date</th>
                <th>To_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for salary in salaries %}
            <tr>
                <td>{{ salary.salary }}</td>
                <td>{{ salary.fromDate ? salary.fromDate|date('Y-m-d') : '' }}</td>
                <td>{{ salary.toDate ? salary.toDate|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_salary_show', {'emp_no': salary.emp_no}) }}">show</a>
                    <a href="{{ path('app_salary_edit', {'emp_no': salary.emp_no}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_salary_new') }}">Create new</a>
{% endblock %}

templates/salary/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Salary{% endblock %}

{% block body %}
    <h1>Create new Salary</h1>

    {{ include('salary/_form.html.twig') }}

    <a href="{{ path('app_salary_index') }}">back to list</a>
{% endblock %}

templates/salary/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Salary{% endblock %}

{% block body %}
    <h1>Salary</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Salary</th>
                <td>{{ salary.salary }}</td>
            </tr>
            <tr>
                <th>From_date</th>
                <td>{{ salary.fromDate ? salary.fromDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>To_date</th>
                <td>{{ salary.toDate ? salary.toDate|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_salary_index') }}">back to list</a>

    <a href="{{ path('app_salary_edit', {'emp_no': salary.emp_no}) }}">edit</a>

    {{ include('salary/_delete_form.html.twig') }}
{% endblock %}